const ERROR_CODE_VALIDATION = 400;
const ERROR_CODE_DEFAULT = 500;
const ERROR_CODE_NOT_FOUND = 404;
const ERROR_CODE_INCORRECT_EMAIL_PASSWORD = 401;
const ERROR_CODE_DUBLICATE = 409;
const ERROR_DEFAULT_MESSAGE = 'Произошла ошибка.';
const PORT = 3000;
const JWT_SECRET = 'SpartakChampion2024';

module.exports = {
  ERROR_CODE_VALIDATION,
  ERROR_CODE_DEFAULT,
  ERROR_CODE_NOT_FOUND,
  ERROR_CODE_INCORRECT_EMAIL_PASSWORD,
  ERROR_CODE_DUBLICATE,
  ERROR_DEFAULT_MESSAGE,
  PORT,
  JWT_SECRET,
};
